import { motion, AnimatePresence } from 'framer-motion';
import { 
  Image as ImageIcon, Video, Mic, Monitor, UploadCloud, Bell, User, 
  FileText, CheckCircle, ShieldAlert, Fingerprint, Activity, AlertTriangle, Info 
} from 'lucide-react';
import { useState, useRef } from 'react';

const options = [
  { id: 'image', label: 'Image', icon: ImageIcon, color: '#4285F4', bg: '#e8f0fe', accepts: 'Supports JPG, PNG, WEBP' },
  { id: 'audio', label: 'Audio', icon: Mic, color: '#FBBC05', bg: '#fef7e0', accepts: 'Supports MP3, WAV, M4A' },
  { id: 'video', label: 'Video', icon: Video, color: '#EA4335', bg: '#fce8e6', accepts: 'Supports MP4, MOV, AVI' },
  { id: 'live', label: 'Live Video', icon: Monitor, color: '#34A853', bg: '#e6f4ea', accepts: 'Connect Stream URL or Source' }
];

export default function Home() {
  const [activeUpload, setActiveUpload] = useState(null);
  const [file, setFile] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [report, setReport] = useState(null);
  const fileInputRef = useRef(null);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setReport(null); // Clear previous report when a new file is added
    }
  };

  const handleOptionClick = (id) => {
    if (activeUpload !== id) {
      setActiveUpload(id);
      setFile(null); 
      setReport(null);
      setIsProcessing(false);
    } else {
      setActiveUpload(null);
      setFile(null);
      setReport(null);
      setIsProcessing(false);
    }
  };

  const handleSubmit = () => {
    setIsProcessing(true);
    // Simulate complex backend analysis delay (e.g. 3.5 seconds)
    setTimeout(() => {
      setIsProcessing(false);
      setReport({
        trustScore: 24,
        accuracy: "99.1%",
        fakePercent: 76,
        riskLevel: "CRITICAL",
        reason: "Detected sophisticated generative traces consistent with deepfake algorithms. Inconsistencies found in lighting physics and micro-texture rendering.",
        proofs: [
          "Facial edge-blending indicates a multi-layer composite overlay.",
          "Spectral analysis reveals abnormal audio-frequency anomalies typically generated by GANs.",
          "Eye reflection light geometry contradicts the environmental light source map detected in the background."
        ]
      });
    }, 3500);
  };

  return (
    <div className="auth-root" style={{ background: '#f8f9fa', minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', position: 'relative', overflowY: 'auto' }}>
      {/* Background Ambience */}
      <div className="login-bg-blob login-bg-blob-1" style={{ zIndex: 0 }} />
      <div className="login-bg-blob login-bg-blob-2" style={{ zIndex: 0 }} />
      
      {/* Main Center Content Container */}
      <motion.div 
        layout
        style={{ 
          position: 'relative', zIndex: 10, width: '100%', maxWidth: '900px', 
          display: 'flex', flexDirection: 'column', alignItems: 'center', 
          paddingTop: '32px', paddingBottom: '60px',
          marginTop: activeUpload ? '100px' : '150px' 
        }}
        transition={{ type: 'spring', bounce: 0.25, duration: 0.6 }}
      >
        <motion.div 
          layout
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          style={{ textAlign: 'center', marginBottom: activeUpload ? '32px' : '56px' }}
        >
          <motion.h1 layout style={{ fontSize: activeUpload ? '28px' : '40px', color: '#202124', fontWeight: '800', letterSpacing: '-1px', marginBottom: '12px' }}>
            {activeUpload ? `Process ${options.find(o => o.id === activeUpload)?.label} Media` : 'Workspace Interface'}
          </motion.h1>
          <motion.p layout style={{ color: '#5f6368', fontSize: activeUpload ? '16px' : '18px', fontWeight: '400' }}>
            {activeUpload ? 'Complete the file upload step securely in your dashboard.' : 'Select an evidence stream below to initiate analysis tracking.'}
          </motion.p>
        </motion.div>

        {/* Dynamic Options System */}
        <motion.div layout style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', justifyContent: 'center', marginBottom: activeUpload ? '32px' : '40px', width: '100%' }}>
          <AnimatePresence mode="popLayout">
            {options.map((opt, i) => {
              if (activeUpload && activeUpload !== opt.id) return null;

              return (
                <motion.div
                  layout
                  key={opt.id}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: activeUpload === opt.id ? 1.05 : 1 }}
                  exit={{ opacity: 0, scale: 0.8, filter: 'blur(5px)' }}
                  transition={{ delay: activeUpload ? 0 : i * 0.05, type: 'spring', stiffness: 200, damping: 20 }}
                  whileHover={{ scale: activeUpload === opt.id ? 1.05 : 1.04, y: activeUpload ? 0 : -6 }}
                  whileTap={{ scale: 0.96 }}
                  onClick={() => handleOptionClick(opt.id)}
                  style={{
                    flex: activeUpload ? '0 1 auto' : '1 1 160px',
                    maxWidth: activeUpload ? '240px' : '190px',
                    background: 'white', 
                    borderRadius: activeUpload ? '18px' : '20px', 
                    padding: activeUpload ? '16px 24px' : '36px 20px', 
                    cursor: 'pointer',
                    display: 'flex', 
                    flexDirection: activeUpload ? 'row' : 'column', 
                    alignItems: 'center', 
                    gap: activeUpload ? '16px' : '16px',
                    boxShadow: activeUpload === opt.id ? `0 0 0 2px ${opt.color}, 0 12px 32px rgba(0,0,0,0.12)` : '0 4px 16px rgba(0,0,0,0.04)',
                    position: 'relative', overflow: 'hidden'
                  }}
                >
                  {activeUpload === opt.id && !activeUpload && <motion.div layoutId="highlight" style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '6px', background: opt.color }} />}
                  <div style={{ background: opt.bg, padding: activeUpload ? '12px' : '20px', borderRadius: '50%' }}>
                    <opt.icon size={activeUpload ? 24 : 36} color={opt.color} />
                  </div>
                  <span style={{ fontWeight: '700', color: '#3c4043', fontSize: activeUpload ? '13px' : '16px', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: activeUpload ? '2px' : '0' }}>{opt.label}</span>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </motion.div>

        {/* Upload & Report Section */}
        <AnimatePresence mode="popLayout">
          {activeUpload && (
            <motion.div
              key="upload-column"
              initial={{ opacity: 0, y: 40, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 20, scale: 0.9 }}
              transition={{ type: 'spring', bounce: 0.35, duration: 0.6 }}
              style={{ width: '100%', maxWidth: '720px', display: 'flex', flexDirection: 'column', gap: '24px' }}
            >
              {/* Drag and Drop Zone */}
              <div 
                style={{ 
                  background: 'white', borderRadius: '24px', padding: '56px 24px', textAlign: 'center', 
                  border: `2px dashed ${options.find(o => o.id === activeUpload)?.color || '#dadce0'}`, 
                  boxShadow: '0 8px 40px rgba(0,0,0,0.06)',
                  display: 'flex', flexDirection: 'column', alignItems: 'center',
                  transition: 'border 0.3s'
                }}
              >
                {!file ? (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                    <UploadCloud size={64} color={options.find(o => o.id === activeUpload)?.color || '#9aa0a6'} style={{ marginBottom: '24px' }} />
                    <h3 style={{ fontSize: '22px', color: '#202124', fontWeight: 'bold', marginBottom: '8px' }}>
                      Drag & Drop your {options.find(o => o.id === activeUpload)?.label} file here
                    </h3>
                    <p style={{ color: '#80868b', marginBottom: '32px', fontSize: '15px' }}>
                      {options.find(o => o.id === activeUpload)?.accepts}
                    </p>
                    <input 
                      type="file" 
                      ref={fileInputRef} 
                      onChange={handleFileChange} 
                      style={{ display: 'none' }} 
                      accept={activeUpload === 'image' ? 'image/*' : activeUpload === 'video' ? 'video/*' : activeUpload === 'audio' ? 'audio/*' : '*'} 
                    />
                    <button 
                      onClick={() => fileInputRef.current?.click()}
                      style={{
                        padding: '14px 40px', background: '#f1f3f4', color: '#202124', border: '1px solid #dadce0', borderRadius: '30px', fontWeight: '600', cursor: 'pointer', fontSize: '16px', transition: 'all 0.2s', boxShadow: '0 2px 8px rgba(0,0,0,0.03)'
                      }}
                      onMouseOver={(e) => { e.currentTarget.style.background = '#e8eaed'; e.currentTarget.style.borderColor = '#d5d9dd'; }}
                      onMouseOut={(e) => { e.currentTarget.style.background = '#f1f3f4'; e.currentTarget.style.borderColor = '#dadce0'; }}
                    >
                      Browse Files
                    </button>
                  </motion.div>
                ) : (
                  <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                     <div style={{ width: '72px', height: '72px', borderRadius: '20px', background: options.find(o => o.id === activeUpload)?.bg, display: 'flex', justifyContent: 'center', alignItems: 'center', marginBottom: '20px' }}>
                        <FileText size={36} color={options.find(o => o.id === activeUpload)?.color} />
                     </div>
                     <span style={{ fontSize: '20px', fontWeight: 'bold', color: '#202124', marginBottom: '8px' }}>{file.name}</span>
                     <span style={{ fontSize: '15px', color: '#5f6368', marginBottom: '32px' }}>{(file.size / 1024 / 1024).toFixed(2)} MB</span>
                     
                     {/* Can only remove file if NOT processing and NO report generated yet */}
                     {!isProcessing && !report && (
                       <button 
                          onClick={() => setFile(null)}
                          style={{ background: 'transparent', border: '1px solid #dadce0', color: '#5f6368', padding: '10px 20px', borderRadius: '20px', cursor: 'pointer', fontSize: '14px', fontWeight: '500', transition: 'all 0.2s' }}
                          onMouseOver={(e) => { e.currentTarget.style.background = '#f8f9fa'; e.currentTarget.style.color = '#EA4335'; e.currentTarget.style.borderColor = '#EA4335'; }}
                          onMouseOut={(e) => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.color = '#5f6368'; e.currentTarget.style.borderColor = '#dadce0'; }}
                       >
                         Remove selection
                       </button>
                     )}
                  </motion.div>
                )}
              </div>

              {/* Action Button: Visible when file is selected and NO report exists */}
              <AnimatePresence mode="wait">
                {file && !report && !isProcessing && (
                   <motion.button
                     key="submit-btn"
                     onClick={handleSubmit}
                     initial={{ opacity: 0, y: 20 }}
                     animate={{ opacity: 1, y: 0 }}
                     exit={{ opacity: 0, scale: 0.9 }}
                     transition={{ type: 'spring', bounce: 0.4 }}
                     style={{
                       width: '100%', padding: '18px', background: options.find(o => o.id === activeUpload)?.color || '#1a73e8', color: 'white', border: 'none', borderRadius: '20px', fontWeight: 'bold', cursor: 'pointer', fontSize: '18px', boxShadow: '0 8px 24px rgba(0,0,0,0.15)', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '12px', transition: 'filter 0.2s'
                     }}
                     onMouseOver={(e) => e.currentTarget.style.filter = 'brightness(1.1)'}
                     onMouseOut={(e) => e.currentTarget.style.filter = 'brightness(1)'}
                   >
                     Initiate Deep Scan
                     <CheckCircle size={22} />
                   </motion.button>
                )}

                {/* Processing State */}
                {isProcessing && (
                  <motion.div 
                    key="processing"
                    initial={{ opacity: 0, height: 0 }} 
                    animate={{ opacity: 1, height: 'auto' }} 
                    exit={{ opacity: 0, height: 0 }} 
                    style={{ padding: '24px', background: 'white', borderRadius: '20px', border: '1px solid #dadce0', display: 'flex', flexDirection: 'column', alignItems: 'center', boxShadow: '0 4px 16px rgba(0,0,0,0.04)' }}
                  >
                     <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: 'linear' }} style={{ marginBottom: '16px' }}>
                       <Activity size={36} color="#1a73e8" />
                     </motion.div>
                     <span style={{ fontSize: '16px', fontWeight: '600', color: '#1a73e8', letterSpacing: '0.5px' }}>Scanning Neural Vectors & Forensics...</span>
                  </motion.div>
                )}

                {/* Generated Intelligence Report */}
                {report && (
                  <motion.div
                    key="report"
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ type: 'spring', bounce: 0.35 }}
                    style={{ width: '100%', background: 'white', borderRadius: '24px', padding: '40px', border: '1px solid #dadce0', boxShadow: '0 12px 48px rgba(0,0,0,0.08)', textAlign: 'left' }}
                  >
                    {/* Report Header */}
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '32px', borderBottom: '1px solid #dadce0', paddingBottom: '24px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                        <div style={{ background: '#fce8e6', padding: '12px', borderRadius: '12px' }}>
                           <ShieldAlert size={32} color="#ea4335" />
                        </div>
                        <div>
                           <h2 style={{ fontSize: '24px', fontWeight: 'bold', margin: '0 0 4px 0', color: '#202124' }}>Intelligence Report</h2>
                           <span style={{ color: '#5f6368', fontSize: '14px' }}>Automated AI Verification Scan complete</span>
                        </div>
                      </div>
                      <div style={{ padding: '8px 20px', background: '#fce8e6', color: '#ea4335', borderRadius: '30px', fontWeight: 'bold', fontSize: '15px', letterSpacing: '1px', boxShadow: '0 2px 8px rgba(234, 67, 53, 0.2)' }}>
                        RISK: {report.riskLevel}
                      </div>
                    </div>

                    {/* Report Metrics Grid */}
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', marginBottom: '40px' }}>
                      <div style={{ background: '#f8f9fa', padding: '24px', borderRadius: '20px', border: '1px solid #dadce0', display: 'flex', flexDirection: 'column', alignItems: 'center', boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.02)' }}>
                        <span style={{ fontSize: '13px', color: '#5f6368', fontWeight: '700', textTransform: 'uppercase', marginBottom: '12px', letterSpacing: '0.5px' }}>Trust Score</span>
                        <span style={{ fontSize: '42px', fontWeight: '900', color: report.trustScore > 50 ? '#34A853' : '#ea4335', lineHeight: '1' }}>{report.trustScore}<span style={{ fontSize: '20px', color: '#9aa0a6', fontWeight: '600' }}>/100</span></span>
                      </div>
                      <div style={{ background: '#f8f9fa', padding: '24px', borderRadius: '20px', border: '1px solid #dadce0', display: 'flex', flexDirection: 'column', alignItems: 'center', boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.02)' }}>
                        <span style={{ fontSize: '13px', color: '#5f6368', fontWeight: '700', textTransform: 'uppercase', marginBottom: '12px', letterSpacing: '0.5px' }}>Fake Probability</span>
                        <span style={{ fontSize: '42px', fontWeight: '900', color: report.fakePercent > 50 ? '#ea4335' : '#34A853', lineHeight: '1' }}>{report.fakePercent}%</span>
                      </div>
                      <div style={{ background: '#f8f9fa', padding: '24px', borderRadius: '20px', border: '1px solid #dadce0', display: 'flex', flexDirection: 'column', alignItems: 'center', boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.02)' }}>
                        <span style={{ fontSize: '13px', color: '#5f6368', fontWeight: '700', textTransform: 'uppercase', marginBottom: '12px', letterSpacing: '0.5px' }}>Scan Accuracy</span>
                        <span style={{ fontSize: '42px', fontWeight: '900', color: '#4285F4', lineHeight: '1' }}>{report.accuracy}</span>
                      </div>
                    </div>

                    {/* Flagging Reason Container */}
                    <div style={{ background: '#fff', borderRadius: '16px', border: '1px solid #fbbc05', padding: '28px', marginBottom: '32px', position: 'relative', overflow: 'hidden', boxShadow: '0 4px 12px rgba(251, 188, 5, 0.08)' }}>
                      <div style={{ position: 'absolute', top: 0, left: 0, bottom: 0, width: '6px', background: '#fbbc05' }} />
                      <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#202124', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <AlertTriangle size={20} color="#fbbc05" /> Reason for Flagging
                      </h4>
                      <p style={{ color: '#3c4043', fontSize: '16px', lineHeight: '1.6', margin: 0 }}>{report.reason}</p>
                    </div>

                    {/* Proofs Breakdown List */}
                    <div>
                      <h4 style={{ fontSize: '18px', fontWeight: 'bold', color: '#202124', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <Fingerprint size={20} color="#1a73e8" /> Forensic Proofs Analyzed
                      </h4>
                      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '16px' }}>
                        {report.proofs.map((proof, idx) => (
                          <li key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', background: '#f8f9fa', padding: '20px', borderRadius: '16px', border: '1px solid #dadce0' }}>
                             <div style={{ background: '#e8f0fe', padding: '8px', borderRadius: '50%', flexShrink: 0 }}>
                               <Info size={20} color="#1a73e8" />
                             </div>
                             <span style={{ fontSize: '15px', color: '#3c4043', lineHeight: '1.6', marginTop: '4px' }}>{proof}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}
